### ISSUE TITLE
YouTube handler debt

### ISSUE THREAD

**Issue by sr229** [awau/Clara#150]
apparently the YT handler can be related to #74 since its the only handler that makes the bot stream drop or jump.

**Comment by Ovyerus** [comment]
This could potentially be related to abalabahaha/eris#213, as we're using ytdl for YouTube, however that issue relates to *streams*, and this issue has persisted through to us caching music streams to files. Perhaps trying to cache a M4A + AAC stream instead of a WebM + Opus stream could fix the issue?

**Comment by sr229** [comment]
@Ovyerus since I've noticed SoundCloud caching are basically MP3 files, this would be more fficient than a native WebM + Opus stream

**Comment by sr229** [comment]
Which I mean in context, is M4A + AAC

**Comment by sr229** [comment]
YouTube Handler debt complete
